version: '3'

services:
  db:
    image: mongo
  bsbuild:
    image: animo/nodebot:latest
    command: yarn start
    volumes:
      - .:/code
      - nodemodules:/code/node_modules
    depends_on:
      - db
    environment:
      - NODE_ENV=dev
      - NODE_PATH=/code/node_modules
    tty: true
  web:
    # build: .
    image: animo/nodebot:latest
    command: yarn js:start
    volumes:
      - .:/code:ro
      # - .:/code:ro
      # - /code/node_modules
      - nodemodules:/code/node_modules:ro
      # - nodemodules:/code/node_modules:ro
    ports:
      - "8080:8080"
    depends_on:
      - db
      # - bsbuild
    environment:
      - NODE_ENV=dev
      - NODE_PATH=/code/node_modules

volumes:
  nodemodules:
